### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by karankankaria** [hklcf/HLS-Player-for-Wordpress#3]
@hklcf Hello, How to use it? Can you please show demo and where to add jw player key?

**Comment by hklcf** [comment]
- install the plugin
- active plugin
- add your jwplayer key in HLS for Wordpress setting

**Comment by karankankaria** [comment]
Okay thanks. Understood!

**Comment by karankankaria** [comment]
What are the shortcodes to use it? and where to add /jwplayer.js

**Comment by karankankaria** [comment]
@hklcf sorry, at first not mentioned you. What are short codes for embeds and where to add /jwplayer.js and what is player id. Hope I am not asking too much

**Comment by hklcf** [comment]
use this short code  `[hls]hls_link[/hls]`

**Comment by karankankaria** [comment]
@hklcf Thanks. Started working. How to add poster and subtitle??

**Comment by karankankaria** [comment]
@hklcf Hello sir. Can you just help with how to add poster and subtitles please

**Comment by karankankaria** [comment]
@hklcf Hello sir, There certain errors like quality option is horizontal menu. how to make it vertical. Also playback rate are in horizontal line

**Comment by KaranJain29** [comment]
@hklcf Please help sir. Example link: https://uwatchfreemovies.site/movie/journey-to-the-center-of-the-earth/

See seetings option in player. Please!!

**Comment by hklcf** [comment]
poster = featured image
subtitles not support yet
